#!/usr/bin/env bash
# transfers a file from our client to a server.

if [ $# -lt 4 ];then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -i StrictHostKeyChecking=no "$4" "$3@$2" "$1":~
fi 
