#!/usr/bin/env bash
# installing nginx on our server
sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > var/www/html/index.nginx-debian.html

sudo service nginx restart
