#!/usr/bin/env bash
# installing nginx on our server
apt-get update
apt-get install -y nginx

sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i '/server {/a \ \ \ \ location /redirect_me { \
\ \ \ \ \ \ \ \ return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4$request_uri; \
\ \ \ \ }' /etc/nginx/sites-enabled/


# Restart Nginx for the changes to take effect
sudo service nginx restart
