#!/usr/bin/env bash
# installing nginx on our server
apt-get update
apt-get install -y nginx

sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

NGINX_CONF="/etc/nginx/nginx.conf"

REDIRECT_BLOCK='location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4}'
sed -i '/location \/redirect_me {/ ,/}/d' "$NGINX_CONF"
sed -i "\$a $REDIRECT_BLOCK" "$NGINX_CONF"

service nginx restart
