#!/usr/bin/env bash
# installing nginx on our server
sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

custom_header="X-Served-By: 168146-web-02"
echo "add_header $custom_header;" | sudo tee -a /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart
